Update 04.connection-management-answers.md
jeuxdeau/http-the-definitive-guide pull request #12
Opened 2019-11-02 03:42 UTC by mgcation

#9

2019-11-02 11:40 UTC, jeuxdeau requested changes
명근님 답변 없어요?

2019-11-10 07:53 UTC, mgcation commented
얼럴뚱땅 넘어가려다가 들킴 ㅜ.ㅜ

2019-11-10 08:09 UTC, mgcation commented on i.http-the-webs-foundation/04.connection-management/04.connection-management-answers.md
> +> 이게 맞는지..?
이 부분을 제대로 이해한 게 맞는지 모르겠어요

2019-11-11 13:04 UTC, jeuxdeau requested changes

2019-11-11 13:04 UTC, jeuxdeau commented on i.http-the-webs-foundation/04.connection-management/04.connection-management-answers.md
> +* Message 기반 : 요청/응답 시 지속 커넥션을 사용하더라도 응답이 오지 않으면 다음 요청을 보낼 수 없으므로 blocking 이 발생한다.
```suggestion
* Message 기반 : 요청/응답 시 요청을 여러 개 보내더라도 서버에서 이전에 온 요청을 처리하고 있는 중이면 이후의 요청에 대해서 blocking 이 발생한다.
```

2019-11-16 10:00 UTC, jeuxdeau approved these changes

2019-11-16 10:00 UTC, jeuxdeau commented
너무 오래돼서 일단 머지합니다

2019-11-16 10:00 UTC, merged